training:
  mode: "both"
  seed: 49
  lr: 1e-4
  epochs: 30
  batch_size: 8
  num_workers: 4
  device: "cuda:0"

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

data:
  num_classes: 140
  class_names_dir: "dataset/annotation/ak_action.csv"
  train_dataset_path: "dataset/embeddings/train_clip_embeddings.h5"
  val_dataset_path:   "dataset/embeddings/val_clip_embeddings.h5"
  frame_diff_dataset_path: "dataset/embeddings/frame_diff_embeddings.h5"

model:
  d_model: 512
  nhead: 8
  num_layers: 4
  dim_feedforward: 2048
  use_cross_attention: false
  use_only_rgb: false
  use_only_flow: true
  use_pe: true
  concat_dim: 1
  dropout: 0.1
  mlp_dropout: 0.1

