training:
  mode: "both"
  seed: 49
  lr: 1e-4
  epochs: 30
  batch_size: 8
  num_workers: 4
  device: "cuda:0"

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

data:
  num_classes: 140
  class_names_dir: "/mnt/Data/enz/AnimalKingdom/action_recognition/annotation/ak_action.csv"
  train_dataset_path: "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/ak_train_clip_vit16.h5"
  val_dataset_path:   "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/ak_val_clip_vit16.h5"
  flow_dataset_path:  "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/flow_embeddings_Atenea_20250325-225147.h5"

model:
  d_model: 512
  nhead: 8
  num_layers: 4
  dim_feedforward: 2048
  use_cross_attention: true
  use_only_rgb: false
  use_only_flow: false
  use_pe: false
  concat_dim: 1
  dropout: 0.1
  mlp_dropout: 0.1

