training:
  mode: "both"
  seed: 49
  model_path: "checkpoints/best_model.pth"
  lr: 1e-4
  epochs: 30
  batch_size: 8
  num_workers: 4
  device: "cuda:0"

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

data:
  num_classes: 140
  class_names_dir: "../dataset/annotations/ak_action.csv"
  train_dataset_path: "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/ak_train_clip_vit32.h5"
  val_dataset_path:   "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/ak_val_clip_vit32.h5"
  frame_diff_dataset_path: "/mnt/Data/enz/AnimalKingdom/action_recognition/dataset/frame_diff_embeddings_Atenea_20250714-173531.h5"

model:
  d_model: 512
  nhead: 8
  num_layers: 4
  dim_feedforward: 2048
  use_cross_attention: false
  use_only_rgb: false
  use_only_flow: false
  use_pe: false
  concat_dim: -1
  dropout: 0.1
  mlp_dropout: 0.1


